CREATE DATABASE IF NOT EXISTS BKBIET;
USE BKBIET;

CREATE TABLE STUDENT (
  ID INT NOT NULL UNIQUE AUTO_INCREMENT,
  FIRSTNAME VARCHAR(50),
  LASTNAME VARCHAR(50),
  GENDER CHAR(1),
  CONSTRAINT GENDER_CHECK CHECK (GENDER IN('M','F')),
  EMAIL VARCHAR(50) UNIQUE,
  LUCKEYNO INT DEFAULT 0,
  PRIMARY KEY(ID)
);

SHOW TABLES;
DESCRIBE STUDENT;

INSERT INTO STUDENT(FIRSTNAME,GENDER,EMAIL,GOODLUCKNO,SPORT) VALUES('RAM','M','RAM123@GMAIL21.COM',10,'CRICKT');
SELECT * FROM STUDENT;

DELETE FROM STUDENT WHERE GENDER = 'M'; 

ALTER TABLE STUDENT ADD SPORT VARCHAR(50);  -- ADD NEW COLUMN 
ALTER TABLE STUDENT MODIFY LUCKEYNO INT DEFAULT 10; -- CHANGE DATATYPE OF AN ATTRIBUTE
ALTER TABLE STUDENT CHANGE COLUMN LUCKEYNO GOODLUCKNO INT DEFAULT 11; -- RENAME COLUMN NAME
ALTER TABLE STUDENT DROP LASTNAME; -- DROP COLUMN
ALTER TABLE STUD RENAME TO STUDENT; -- RENAME TABLE NAME
