CREATE DATABASE IF NOT EXISTS BKBIET;
USE BKBIET;

CREATE TABLE STUDENT (
  ROLLNO INT AUTO_INCREMENT UNIQUE,
  FIRSTNAME VARCHAR(50),
  LASTNAME VARCHAR(50),
  AGE INT
);

ALTER TABLE STUDENT ADD PRIMARY KEY (ROLLNO);
SHOW TABLES;
SELECT * FROM STUDENT;
DESCRIBE STUDENT;

INSERT INTO STUDENT (FIRSTNAME, LASTNAME, AGE) VALUES('SUMIT','JANGIR', 22);
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, AGE) VALUES('UDAY','JANGIR', 21);
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, AGE) VALUES('NIKITA','JANGIR', 21);
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, AGE) VALUES('ABHISHEK','JANGIR', 23);
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, AGE) VALUES('HIMANSHU','JANGIR', 24);
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, AGE) VALUES('RIKITA','JANGID', 25);
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, AGE) VALUES('RAHUL','JANGID', 20);


-- ORDER OF EXEXUTION FROM RIGHT TO LEFT

SELECT * FROM STUDENT WHERE AGE >= 22;
SELECT * FROM STUDENT WHERE AGE BETWEEN 21 AND 23;
SELECT * FROM STUDENT WHERE FIRSTNAME IN ('SUMIT','UDAY','RAHUL');

SELECT * FROM STUDENT WHERE FIRSTNAME IN ('SUMIT') AND AGE > 20;
SELECT * FROM STUDENT WHERE FIRSTNAME IN ('SUMIT') OR AGE > 23;
SELECT * FROM STUDENT WHERE FIRSTNAME NOT IN ('SUMIT', 'HIMANSHU');

SELECT * FROM STUDENT WHERE LASTNAME IS NULL;

SELECT * FROM STUDENT ORDER BY FIRSTNAME DESC;
SELECT * FROM STUDENT ORDER BY AGE ASC;

SELECT ROLLNO, FIRSTNAME, LASTNAME FROM STUDENT WHERE AGE > 22 GROUP BY ROLLNO, FIRSTNAME, LASTNAME;

SELECT DISTINCT(AGE) FROM STUDENT;
SELECT AGE FROM STUDENT GROUP BY AGE;